/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SnapshotsRouteImport } from './routes/snapshots'
import { Route as ReportsAndMetricsRouteImport } from './routes/reportsAndMetrics'
import { Route as RemoteReplicationRouteImport } from './routes/remoteReplication'
import { Route as ConfigurationRouteImport } from './routes/configuration'
import { Route as IndexRouteImport } from './routes/index'

const SnapshotsRoute = SnapshotsRouteImport.update({
  id: '/snapshots',
  path: '/snapshots',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsAndMetricsRoute = ReportsAndMetricsRouteImport.update({
  id: '/reportsAndMetrics',
  path: '/reportsAndMetrics',
  getParentRoute: () => rootRouteImport,
} as any)
const RemoteReplicationRoute = RemoteReplicationRouteImport.update({
  id: '/remoteReplication',
  path: '/remoteReplication',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfigurationRoute = ConfigurationRouteImport.update({
  id: '/configuration',
  path: '/configuration',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/configuration': typeof ConfigurationRoute
  '/remoteReplication': typeof RemoteReplicationRoute
  '/reportsAndMetrics': typeof ReportsAndMetricsRoute
  '/snapshots': typeof SnapshotsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/configuration': typeof ConfigurationRoute
  '/remoteReplication': typeof RemoteReplicationRoute
  '/reportsAndMetrics': typeof ReportsAndMetricsRoute
  '/snapshots': typeof SnapshotsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/configuration': typeof ConfigurationRoute
  '/remoteReplication': typeof RemoteReplicationRoute
  '/reportsAndMetrics': typeof ReportsAndMetricsRoute
  '/snapshots': typeof SnapshotsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/configuration'
    | '/remoteReplication'
    | '/reportsAndMetrics'
    | '/snapshots'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/configuration'
    | '/remoteReplication'
    | '/reportsAndMetrics'
    | '/snapshots'
  id:
    | '__root__'
    | '/'
    | '/configuration'
    | '/remoteReplication'
    | '/reportsAndMetrics'
    | '/snapshots'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConfigurationRoute: typeof ConfigurationRoute
  RemoteReplicationRoute: typeof RemoteReplicationRoute
  ReportsAndMetricsRoute: typeof ReportsAndMetricsRoute
  SnapshotsRoute: typeof SnapshotsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/snapshots': {
      id: '/snapshots'
      path: '/snapshots'
      fullPath: '/snapshots'
      preLoaderRoute: typeof SnapshotsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reportsAndMetrics': {
      id: '/reportsAndMetrics'
      path: '/reportsAndMetrics'
      fullPath: '/reportsAndMetrics'
      preLoaderRoute: typeof ReportsAndMetricsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/remoteReplication': {
      id: '/remoteReplication'
      path: '/remoteReplication'
      fullPath: '/remoteReplication'
      preLoaderRoute: typeof RemoteReplicationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuration': {
      id: '/configuration'
      path: '/configuration'
      fullPath: '/configuration'
      preLoaderRoute: typeof ConfigurationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConfigurationRoute: ConfigurationRoute,
  RemoteReplicationRoute: RemoteReplicationRoute,
  ReportsAndMetricsRoute: ReportsAndMetricsRoute,
  SnapshotsRoute: SnapshotsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
