/* tslint:disable */
/* eslint-disable */
/**
 * Btrfs Backup System API
 * API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CreateNewServerRequest,
} from '../models/index';
import {
    CreateNewServerRequestFromJSON,
    CreateNewServerRequestToJSON,
} from '../models/index';

export interface ServersPostRequest {
    createNewServerRequest?: CreateNewServerRequest;
}

/**
 * 
 */
export class RemoteServersApi extends runtime.BaseAPI {

    /**
     * Create new remote server
     */
    async serversPostRaw(requestParameters: ServersPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/servers`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateNewServerRequestToJSON(requestParameters['createNewServerRequest']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Create new remote server
     */
    async serversPost(requestParameters: ServersPostRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.serversPostRaw(requestParameters, initOverrides);
    }

}
