/* tslint:disable */
/* eslint-disable */
/**
 * Btrfs Backup System API
 * API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateNewServerRequest
 */
export interface CreateNewServerRequest {
    /**
     * 
     * @type {string}
     * @memberof CreateNewServerRequest
     */
    ipAddress: string;
    /**
     * 
     * @type {string}
     * @memberof CreateNewServerRequest
     */
    username: string;
    /**
     * 
     * @type {string}
     * @memberof CreateNewServerRequest
     */
    password: string;
}

/**
 * Check if a given object implements the CreateNewServerRequest interface.
 */
export function instanceOfCreateNewServerRequest(value: object): value is CreateNewServerRequest {
    if (!('ipAddress' in value) || value['ipAddress'] === undefined) return false;
    if (!('username' in value) || value['username'] === undefined) return false;
    if (!('password' in value) || value['password'] === undefined) return false;
    return true;
}

export function CreateNewServerRequestFromJSON(json: any): CreateNewServerRequest {
    return CreateNewServerRequestFromJSONTyped(json, false);
}

export function CreateNewServerRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateNewServerRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'ipAddress': json['ipAddress'],
        'username': json['username'],
        'password': json['password'],
    };
}

export function CreateNewServerRequestToJSON(json: any): CreateNewServerRequest {
    return CreateNewServerRequestToJSONTyped(json, false);
}

export function CreateNewServerRequestToJSONTyped(value?: CreateNewServerRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'ipAddress': value['ipAddress'],
        'username': value['username'],
        'password': value['password'],
    };
}

