/* tslint:disable */
/* eslint-disable */
/**
 * Btrfs Backup System API
 * API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from './configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from './common';
import type { RequestArgs } from './base';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, BaseAPI, RequiredError, operationServerMap } from './base';

export interface CreateNewServerRequest {
    'name': string;
    'ipAddress': string;
    'port'?: number;
    'username': string;
    'password': string;
    'isPrimary'?: boolean;
}
export interface CreateNewServerResponse {
    'uid': string;
    'ipAddress': string;
    'port'?: number;
    'isPrimary'?: boolean;
}
export interface GetAllServersResponse {
    'uid': string;
    'name': string;
    'ipAddress': string;
    'port'?: number;
    'isPrimary'?: boolean;
}
export interface GetHealthCheckAllResponseInner {
    'uid': string;
    'online'?: boolean;
}
export interface UpdateServerRequest {
    'name'?: string;
    'ipAddress'?: string;
    'port'?: number;
    'username'?: string;
    'password'?: string;
    'isPrimary'?: boolean;
}

/**
 * RemoteServersApi - axios parameter creator
 */
export const RemoteServersApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiServersGet: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/servers`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiServersHealthCheckGet: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/servers/healthCheck`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary 
         * @param {CreateNewServerRequest} [createNewServerRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiServersPost: async (createNewServerRequest?: CreateNewServerRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/servers`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(createNewServerRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary 
         * @param {string} uid 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiServersUidDelete: async (uid: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'uid' is not null or undefined
            assertParamExists('apiServersUidDelete', 'uid', uid)
            const localVarPath = `/api/servers/{uid}`
                .replace(`{${"uid"}}`, encodeURIComponent(String(uid)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary 
         * @param {string} uid 
         * @param {UpdateServerRequest} [updateServerRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiServersUidPut: async (uid: string, updateServerRequest?: UpdateServerRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'uid' is not null or undefined
            assertParamExists('apiServersUidPut', 'uid', uid)
            const localVarPath = `/api/servers/{uid}`
                .replace(`{${"uid"}}`, encodeURIComponent(String(uid)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(updateServerRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * RemoteServersApi - functional programming interface
 */
export const RemoteServersApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = RemoteServersApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiServersGet(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<GetAllServersResponse>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiServersGet(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['RemoteServersApi.apiServersGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiServersHealthCheckGet(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<GetHealthCheckAllResponseInner>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiServersHealthCheckGet(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['RemoteServersApi.apiServersHealthCheckGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary 
         * @param {CreateNewServerRequest} [createNewServerRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiServersPost(createNewServerRequest?: CreateNewServerRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CreateNewServerResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiServersPost(createNewServerRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['RemoteServersApi.apiServersPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary 
         * @param {string} uid 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiServersUidDelete(uid: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiServersUidDelete(uid, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['RemoteServersApi.apiServersUidDelete']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary 
         * @param {string} uid 
         * @param {UpdateServerRequest} [updateServerRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiServersUidPut(uid: string, updateServerRequest?: UpdateServerRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiServersUidPut(uid, updateServerRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['RemoteServersApi.apiServersUidPut']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * RemoteServersApi - factory interface
 */
export const RemoteServersApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = RemoteServersApiFp(configuration)
    return {
        /**
         * 
         * @summary 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiServersGet(options?: RawAxiosRequestConfig): AxiosPromise<Array<GetAllServersResponse>> {
            return localVarFp.apiServersGet(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiServersHealthCheckGet(options?: RawAxiosRequestConfig): AxiosPromise<Array<GetHealthCheckAllResponseInner>> {
            return localVarFp.apiServersHealthCheckGet(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary 
         * @param {CreateNewServerRequest} [createNewServerRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiServersPost(createNewServerRequest?: CreateNewServerRequest, options?: RawAxiosRequestConfig): AxiosPromise<CreateNewServerResponse> {
            return localVarFp.apiServersPost(createNewServerRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary 
         * @param {string} uid 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiServersUidDelete(uid: string, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.apiServersUidDelete(uid, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary 
         * @param {string} uid 
         * @param {UpdateServerRequest} [updateServerRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiServersUidPut(uid: string, updateServerRequest?: UpdateServerRequest, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.apiServersUidPut(uid, updateServerRequest, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * RemoteServersApi - object-oriented interface
 */
export class RemoteServersApi extends BaseAPI {
    /**
     * 
     * @summary 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public apiServersGet(options?: RawAxiosRequestConfig) {
        return RemoteServersApiFp(this.configuration).apiServersGet(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public apiServersHealthCheckGet(options?: RawAxiosRequestConfig) {
        return RemoteServersApiFp(this.configuration).apiServersHealthCheckGet(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary 
     * @param {CreateNewServerRequest} [createNewServerRequest] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public apiServersPost(createNewServerRequest?: CreateNewServerRequest, options?: RawAxiosRequestConfig) {
        return RemoteServersApiFp(this.configuration).apiServersPost(createNewServerRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary 
     * @param {string} uid 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public apiServersUidDelete(uid: string, options?: RawAxiosRequestConfig) {
        return RemoteServersApiFp(this.configuration).apiServersUidDelete(uid, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary 
     * @param {string} uid 
     * @param {UpdateServerRequest} [updateServerRequest] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public apiServersUidPut(uid: string, updateServerRequest?: UpdateServerRequest, options?: RawAxiosRequestConfig) {
        return RemoteServersApiFp(this.configuration).apiServersUidPut(uid, updateServerRequest, options).then((request) => request(this.axios, this.basePath));
    }
}



